#!/bin/bash
./mkpage intro
./mkpage tools
./mkpage canvas
./mkpage first
./mkpage vars
./mkpage coord
./mkpage colors
./mkpage text
./mkpage image
./mkpage graphics
./mkpage fgraphics
./mkpage list
./mkpage chart
./mkpage loop
./mkpage geo -layers="rect:image:poly:ellipse:text:line:list"
./mkpage region
./mkpage refs
./mkpage example -pagesize=Widescreen
./mkpage hero
./mkpage twoup
./mkpage fourup
./mkpage imt
./mkpage plain
./mkpage lamp
sans=PublicSans-Regular
mono=Inconsolata-Medium
serif=Charter-Regular
decksh tut.dsh |
pdfdeck -sw \
 -pagesize Letter \
 -layers="rect:image:poly:ellipse:text:line:list" \
 -stdout \
 -sans $sans \
 -mono $mono \
 -serif $serif - > tut.pdf
open tut.pdf
