#!/bin/bash
cw=1200
ch=300
latmax=60
latmin="0"

longmax=160
longmin="-160"
latlong="-latmax $latmax -latmin $latmin -longmax $longmax -longmin $longmin"
bgcolor="steelblue" # rgb(15,26,49)"
eacolor="linen" # rgb(179,119,109)"
dotcolor="red:50"
dotsize="0.75"
textcolor="gray"
textsize="0.5"
# combine map with locations
(
	echo '<deck>'
    echo "<slide bg=\"$bgcolor\" fg=\"$eacolor\">"
    echo "<text    xp=\"5\" yp=\"20\" sp=\"1\">The Travels of W.E.B Du Bois (1882-1961)</text>"
    echo "<text    xp=\"5.5\" yp=\"15\" sp=\"0.5\">Place Visited</text>"
    echo "<ellipse xp=\"5\" yp=\"16\" hr=\"100\" wp=\"0.5\" color=\"red\" opacity=\"50\"/>"
    world    $latlong \
             -fulldeck=f \
             -style deck \
             -shape fill \
             -color "$eacolor"   world.kml
	awk --csv '{print $1, $2}' dubois-locations.csv | 
	geodeck $latlong \
            -fulldeck=f \
            -style deck \
            -shape dot  \
            -color $dotcolor \
            -shapesize $dotsize \
            -autobbox=f 
    echo '</slide>'
    echo '</deck>'
)  | pdfdeck -layers poly:ellipse:text -pagesize ${cw}x${ch} -stdout - > f.pdf