#!/bin/sh
serif=PublicSans-Bold
sans=PublicSans-Regular
mono="Inconsolata-Light"
decksh tuskegee.dsh > tuskegee.xml
case "$1" in
	both)
		shift
		pdfdeck -mono $mono -sans $sans -serif $serif -pagesize 1584,2016 $* tuskegee.xml
		pngdeck -mono $mono -sans $sans -serif $serif -pagesize 1584,2016 $* tuskegee.xml
		;;
	png)
		shift
		pngdeck -mono $mono -sans $sans -serif $serif -pagesize 1584,2016 $* tuskegee.xml
		;;
	victory)
		decksh victory.dsh | pdfdeck -pagesize Letter -stdout -sans $sans -serif Charter-Italic - > victory.pdf
		;;
	*)
		pdfdeck -mono $mono -sans $sans -serif $serif -pagesize 1584,2016 $* tuskegee.xml
esac

