#!/bin/bash
decksh ww2.dsh   | pdfdeck -sans Inconsolata-Medium -layers=poly:line:curve:ellipse:text:rect:list -pagesize 1000x800 -stdout - > ww2.pdf
decksh torch.dsh | pdfdeck -pagesize 1500x500 -layers=poly:rect:text:ellipse:image -stdout - > torch.pdf
