#!/bin/bash
decksh seneca.dsh       | pdfdeck -stdout -sans Baskervville-Italic  - > seneca.pdf
decksh pop.dsh          | pdfdeck -stdout                            - >  pop.pdf
decksh weeksville.dsh   | pdfdeck -stdout -sans Baskervville-Italic  - > weeksville.pdf