#!/bin/sh
if test $# -ne 2
then
	echo specify layout file and input file >2&1
	exit 1
fi
awk 'NR == 1 {print $0} NR > 1 {print $1 "\t" $2 "\t" $3}' $1 > f1
awk 'NR == 1 {print $0} NR > 1 {print $4 "\t" $5}' $2 > f2
paste f1 f2 > nyt-$i

