#!/bin/sh
decksh astrobang.dsh|pdfdeck -pagesize 1920,1080 -serif NotoSerif-Italic -sans NotoSans-Regular $* -stdout - > astrobang.pdf
decksh astrobang.dsh|pngdeck -pagesize 1920,1080 -serif NotoSerif-Italic -sans NotoSans-Regular $*  /dev/stdin  && mv stdin-00001.png astrobang.png
